export const SCREEN_PATH = {
  TOP: '/',
  SIGN_IN: 'sign-in',
  SIGN_UP: 'sign-up',
  SIGN_UP_CONFIRM: 'sign-up-confirm',
  SIGN_UP_VERIFY: 'sign-up-verify',
  PASSWORD_RESET: 'password-reset',
  PASSWORD_RESET_REQUEST_DONE: 'password-reset-request-done',
  PASSWORD_RESET_VERIFY: 'password-reset-verify',
  TERM_OF_SERVICE: 'others-term-of-service',
  TRADE_LAW: 'others-trade-law',
  BOX_DETAIL: 'box-detail',
  BOX_RESULT: 'box-result',
  CARD_DETAIL: 'card-detail',
  ACQUISITION_HISTORY: 'acquisition-history',
  ACQUISITION_DETAIL: 'acquisition-detail',
  SETTING_ADDRESS: 'setting-address',
  SETTING_ADD_ADDRESS: 'setting-address-add',
  SETTING_CHANGE_ADDRESS: 'setting-address-change',
  SETTING_DETAIL_ADDRESS: 'setting-address-detail',
  DELIVERY_SHIPPING_PRODUCTS: 'delivery-shipping-product',
  POINT_PURCHASE: 'point-purchase',
  POINT_PURCHASE_SUCCESS: 'point-purchase-success',
  POINT_PURCHASE_ERROR: 'point-purchase-error',
  POINT_HISTORY: 'point-history',
  SETTING_PROFILE: 'setting-profile',
  SETTING_PASSWORD: 'setting-password',
}
